/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dangeloranabinimagazzino;

/**
 *
 * @author ranasgalla.niccolo
 */
public class FrameProdotto extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameProdotto.class.getName());

    private GestioneProdotto gp;
    private GestioneKey k;

    /**
     * Creates new form FrameProdotto
     */
    public FrameProdotto() {
        initComponents();
        gp = new GestioneProdotto();
        k = new GestioneKey();
    }

    private void btnCaricaActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String nome = txtNome.getText().trim();
            double prezzoA = Double.parseDouble(txtPrezzoA.getText());
            double prezzoV = Double.parseDouble(txtPrezzoV.getText());
            int scorta = Integer.parseInt(txtScorta.getText());
            int scortaMin = Integer.parseInt(txtScortaMin.getText());

            int nuovoId = k.getNuovoId();

            Prodotto p = new Prodotto(nuovoId, nome, prezzoA, prezzoV, scorta, scortaMin, 0);
            gp.scrivi(p);

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Prodotto caricato con successo!\nID assegnato: " + nuovoId,
                    "Successo", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Pulisce i campi dopo il salvataggio
            txtNome.setText("");
            txtPrezzoA.setText("");
            txtPrezzoV.setText("");
            txtScorta.setText("");
            txtScortaMin.setText("");

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Errore: inserisci valori numerici validi.",
                    "Errore", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        txtPrezzoA = new javax.swing.JTextField();
        txtPrezzoV = new javax.swing.JTextField();
        txtScorta = new javax.swing.JTextField();
        txtScortaMin = new javax.swing.JTextField();
        btnCarica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 140, -1));

        txtPrezzoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezzoAActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrezzoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 140, -1));
        getContentPane().add(txtPrezzoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 140, -1));
        getContentPane().add(txtScorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 140, -1));
        getContentPane().add(txtScortaMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 140, -1));

        btnCarica.setText("Carica");
        btnCarica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaricaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarica, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dangeloranabinimagazzino/sfondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtPrezzoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezzoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezzoAActionPerformed

    private void btnCaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaActionPerformed
        // TODO add your handling code here:
        String nome = txtNome.getText();
        String num = txtPrezzoA.getText();
        int prezzoA = Integer.parseInt(num);
        num = txtPrezzoV.getText();
        int prezzoV = Integer.parseInt(num);
        num = txtScorta.getText();
        int scorta = Integer.parseInt(num);
        num = txtScortaMin.getText();
        int scortaMin = Integer.parseInt(num);

    }//GEN-LAST:event_btnCaricaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameProdotto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPrezzoA;
    private javax.swing.JTextField txtPrezzoV;
    private javax.swing.JTextField txtScorta;
    private javax.swing.JTextField txtScortaMin;
    // End of variables declaration//GEN-END:variables
}
