/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dangeloranabinimagazzino;

import javax.swing.JOptionPane;

/**
 *
 * @author ranasgalla.niccolo
 */
public class FrameProdotto extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameProdotto.class.getName());

    private GestioneProdotto gp;
    private GestioneKey k;

    /**
     * Creates new form FrameProdotto
     */
    public FrameProdotto() {
        initComponents();
        gp = new GestioneProdotto();
        k = new GestioneKey();
    }

    private void pulisciCampi() {
        txtNome.setText("");
        txtPrezzoA.setText("");
        txtPrezzoV.setText("");
        txtScorta.setText("");
        txtScortaMin.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        txtPrezzoA = new javax.swing.JTextField();
        txtPrezzoV = new javax.swing.JTextField();
        txtScorta = new javax.swing.JTextField();
        txtScortaMin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnApri = new javax.swing.JButton();
        btnCarica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 210, 30));

        txtPrezzoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezzoAActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrezzoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 210, 30));
        getContentPane().add(txtPrezzoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 210, 30));
        getContentPane().add(txtScorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 210, 30));
        getContentPane().add(txtScortaMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Scorta Minima");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 50, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prezzo Acquisto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Prezzo Vendita");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Scorta");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 70, 30));

        btnApri.setBackground(new java.awt.Color(21, 21, 101));
        btnApri.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnApri.setForeground(new java.awt.Color(255, 255, 255));
        btnApri.setText("APRI MAGAZZINO!");
        btnApri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApriActionPerformed(evt);
            }
        });
        getContentPane().add(btnApri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 850, 100));

        btnCarica.setBackground(new java.awt.Color(21, 21, 101));
        btnCarica.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnCarica.setForeground(new java.awt.Color(255, 255, 255));
        btnCarica.setText("Carica");
        btnCarica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaricaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarica, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 210, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dangeloranabinimagazzino/sfondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtPrezzoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezzoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezzoAActionPerformed

    private void btnApriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApriActionPerformed
        // TODO add your handling code here:

        FrameMagazzino magazzino = new FrameMagazzino();
        magazzino.setVisible(true);
    }//GEN-LAST:event_btnApriActionPerformed

    private void btnCaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaActionPerformed
        // TODO add your handling code here:
        try {
            
            String nome = txtNome.getText().trim();
            if (nome.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Il nome non può essere vuoto");
                return;
            }

            double prezzoA = Double.parseDouble(txtPrezzoA.getText());
            double prezzoV = Double.parseDouble(txtPrezzoV.getText());
            int scorta = Integer.parseInt(txtScorta.getText());
            int scortaMin = Integer.parseInt(txtScortaMin.getText());

            //Generazione nuovo ID tramite GestioneKey
            int nuovoId = k.getNuovoId();

            //Creazione oggetto Prodotto (inizialmente 0 prodotti venduti)
            Prodotto p = new Prodotto(nuovoId, nome, prezzoA, prezzoV, scorta, scortaMin, 0);

            //Scrittura su file tramite GestioneProdotto
            gp.scrivi(p);

            JOptionPane.showMessageDialog(this, "Prodotto caricato con successo! ID: " + nuovoId);
            
            //Pulizia campi
            pulisciCampi();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"inserire valori numerici validi nei campi prezzo e scorta.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "durante il salvataggio: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCaricaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApri;
    private javax.swing.JButton btnCarica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPrezzoA;
    private javax.swing.JTextField txtPrezzoV;
    private javax.swing.JTextField txtScorta;
    private javax.swing.JTextField txtScortaMin;
    // End of variables declaration//GEN-END:variables
}
